apiVersion: apps/v1
kind: Deployment
metadata:
  name: hazelcast-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hazelcast
  template:
    metadata:
      labels:
        app: hazelcast
    spec:
      serviceAccountName: hazelcast-service-account
      containers:
        - name: hazelcast
          image: prakashsharma91/hazelcast-demo
          env:
            - name: environment
              value: "k8s"
            - name: service-name
              value: "hazelcast-service"
          resources:
            limits:
              memory: "1024Mi"
              cpu: "500m"
          ports:
            - name: "http"
              containerPort: 8080
              protocol: TCP
            - name: "hz"
              containerPort: 5701
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: hazelcast-service
spec:
  type: NodePort
  selector:
    app: hazelcast
  ports:
    - name: "http"
      port: 8080
      targetPort: 8080
    - name: "hz"
      port: 5701
      targetPort: 5701